version: "3.4"

services:
  mymongo:
    image: mongo
    container_name: dash_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: achandrapaul_dev
      MONGO_INITDB_ROOT_PASSWORD: 123456789
      MONGO_INITDB_DATABASE: resume
    volumes:
      - type: volume
        source: data
        target: /data/db
    ports:
      - 27017:27017
      - 28017:28017
    healthcheck:
      test: "exit 0"

  dash_api:
    container_name: dash_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 5678:5678
    env_file:
      - .env
    depends_on:
      - mymongo
    links:
      - mymongo
    environment:
      INITDB_ROOT_USERNAME: achandrapaul_dev
      INITDB_ROOT_PASSWORD: 123456789
      DB_HOST: mymongo
      DB_PORT: 27017
      INITDB_DATABASE: admin

  ui:
    container_name: dashboard_ui
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - dash_api
    links:
      - mymongo
    environment:
      API_HOST: dash_api
      API_PORT: 5000

volumes:
  data:
